version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
     - "4000:80"
    volumes:
     - .:/app
  db:
    image: postgres:9.5.4
    restart: always
    ports:
      - "5432"
